---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  # namespace: csye7125
  # labels:
  #   app: myapp

spec:
    containers:
    - name: webapp-container
      image: httpd:2.4
      # imagePullPolicy: IfNotPresent
      restartPolicy: 
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name: key1-env
          valueFrom:
            configMapKeyRef:
              name: config
              key: key1
        - name: secret-env
          valueFrom:
            secretKeyRef:
              name: secret
              key: secret.file

      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3

      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 2

      startupProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 5
        failureThreshold: 10
