---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  # namespace: csye7125
  # labels:
  #   app: myapp

spec:
  containers:
    - name: webapp-container
      image: dongrep/static-site
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: port
          valueFrom:
            configMapKeyRef:
              name: config
              key: port
        - name: secret-env
          valueFrom:
            secretKeyRef:
              name: secret
              key: secret.file

      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3

      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 2

      startupProbe:
        httpGet:
          path: /
          port: 8080
        periodSeconds: 5
        failureThreshold: 10

  imagePullSecrets:
    - name: dockercred
